version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: envexplorer-api
    env_file:
      - .env
      - docker-local.env

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: envexplorer-client
    ports: 
      - "5102:80"