name: 'tauri-build'
on:
  push:
    branches:
      - release-tauri-app

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: publish
        uses: JonasKruckenberg/tauri-build@v1.0.3
        with:
          projectPath: ../client
